### ISSUE TITLE
ImportError: cannot import name 'escape' from 'jinja2'

### ISSUE THREAD

**Issue by drlight17** [Privex/postfix-parser#11]
Hello. Just fresh installed postfix-parser on Ubuntu Server 20.04 LTS using instruction, but when I test run ./run.sh parse the following error is occured:
`
Loading .env environment variables...
Traceback (most recent call last):
  File "./manage.py", line 70, in <module>
    args.func(args)
  File "./manage.py", line 55, in runparse
    from postfixparser.main import main
  File "/home/mailparser/postfix-parser/postfixparser/main.py", line 25, in <module>
    from postfixparser.core import get_rethink
  File "/home/mailparser/postfix-parser/postfixparser/core.py", line 26, in <module>
    from quart import request
  File "/home/mailparser/.local/share/virtualenvs/postfix-parser-GwLl7qfX/lib/python3.8/site-packages/quart/__init__.py", line 3, in <module>
    from jinja2 import escape, Markup
ImportError: cannot import name 'escape' from 'jinja2' (/home/mailparser/.local/share/virtualenvs/postfix-parser-GwLl7qfX/lib/python3.8/site-packages/jinja2/__init__.py)
`
What does it mean and how to fix it? Thanks.

**Comment by drlight17** [comment]
It was a long time ago. Since then I started [my fork](https://github.com/drlight17/mta-log-parser) of this project that is slowloy becoming more independent. 
As this is no longer needed I close the issue.
