### ISSUE TITLE
Setup Issue with Python38

### ISSUE THREAD

**Issue by BerndHelber** [Privex/postfix-parser#9]
Hello Privex Team,

possibly the Problem exists between  Keyboard and Chair. 
But i tried to setup postfix-parser on different Systems based on CentOS 7, once with self compiled Python 3.7 and later on with Software Collection RPM's
Unfortunately there seem to be an underlying issue, maybe it has to do with the PATH Variables .
But the provided Build Instructions don't work flawlessly as expected.

It doesn't matter if i install the missing packages with pip --user Optio or  into  the Python distribution.

running the service via 
run.sh prod 
```

ModuleNotFoundError: No module named 'quart.exceptions'
Process Process-1:
Traceback (most recent call last):
  File "/opt/rh/rh-python38/root/usr/lib64/python3.8/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/opt/rh/rh-python38/root/usr/lib64/python3.8/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/opt/rh/rh-python38/root/usr/local/lib64/python3.8/site-packages/hypercorn/asyncio/run.py", line 178, in asyncio_worker
    app = load_application(config.application_path)
  File "/opt/rh/rh-python38/root/usr/local/lib64/python3.8/site-packages/hypercorn/utils.py", line 110, in load_application
    module = import_module(import_name)
  File "/opt/rh/rh-python38/root/usr/lib64/python3.8/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 783, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/mailparser/postfix-parser/wsgi.py", line 19, in <module>
    from postfixparser.webui import app
  File "/home/mailparser/postfix-parser/postfixparser/webui.py", line 27, in <module>
    from postfixparser import settings, api
  File "/home/mailparser/postfix-parser/postfixparser/api.py", line 10, in <module>
    from .core import get_accepts
  File "/home/mailparser/postfix-parser/postfixparser/core.py", line 27, in <module>
    from quart.exceptions import BadRequest
ModuleNotFoundError: No module named 'quart.exceptions'
 
```

i'll face the same problem, only to mention  i'll checked with pipreqs if i miss any dependencies
`
pipreqs /home/mailparser/postfix-parser/`
`pip install --user -r requirements.txt`

Possibly you may give me hint, cause i have the feeling there's a detail i  may have overseen.
 Kind regards

[log.txt](https://github.com/Privex/postfix-parser/files/6645685/log.txt)

**Comment by Someguy123** [comment]
Hi,

I'm setting up a blank docker VM now to investigate the issue.

Though the first issue I see, is that you seem to have installed the requirements globally somehow, while the instructions in the README use a `pipenv` virtual environment.

How did you install the requirements globally? Did you manually convert the Pipfile into a requirements.txt? Did you simply freeze pip from within the pipenv virtualenv?

**Comment by Someguy123** [comment]
I've fixed the issue in tag 1.1.2 ( commit a048543df01aacde140e7299a5b6a935a5013047 ) 👍 

Apparently `quart.exceptions.BadRequest` was just an alias to `werkzeug.exceptions.BadRequest` - so it was removed in a newer version of Quart at some point. I've fixed the import to load it from werkzeug and now it seems to run just fine.

Simply run `git pull` - and assuming you've got the right deps from Pipfile/Pipfile.lock - it should run on Python 3.7, 3.8 and 3.9

Please confirm whether or not this fixes your issue. If it does, then I'll close the ticket, otherwise I'll continue trying to help you resolve the issue.

**Comment by BerndHelber** [comment]
Hello thanks for the quick response.
i tried both ways globally and localy too. Firstly i started with the local Environment which showed the same effects.


Pipfile.lock (723ea8) out of date, updating to (12de09)...
Locking [dev-packages] dependencies...
Locking [packages] dependencies...
Building requirements...
Resolving dependencies...
✔ Success!
Updated Pipfile.lock (12de09)!
Installing dependencies from Pipfile.lock (12de09)...
  🐍   ▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉ 7/26 — 00:00:00
To activate this project's virtualenv, run pipenv shell.
Alternatively, run a command inside the virtualenv with pipenv run.

Alternatively, run a command inside the virtualenv with pipenv run.
[mailparser@mta postfix-parser]$ pipenv shell
Launching subshell in virtual environment...
[mailparser@mta postfix-parser]$  . /home/mailparser/.local/share/virtualenvs/postfix-parser-GwLl7qfX/bin/activate
(postfix-parser) [mailparser@mta postfix-parser]$ 

(postfix-parser) [mailparser@mta postfix-parser]$ cp example.env .env
(postfix-parser) [mailparser@mta postfix-parser]$ ./run.sh prod
Loading .env environment variables...
[2021-06-14 07:25:34 +0200] [10914] [INFO] Running on http://127.0.0.1:8487 (CTRL + C to quit)
[2021-06-14 07:25:34 +0200] [10909] [INFO] Running on http://127.0.0.1:8487 (CTRL + C to quit)
[2021-06-14 07:25:34 +0200] [10911] [INFO] Running on http://127.0.0.1:8487 (CTRL + C to quit)
[2021-06-14 07:25:34 +0200] [10910] [INFO] Running on http://127.0.0.1:8487 (CTRL + C to quit)
[2021-06-14 07:25:34 +0200] [10912] [INFO] Running on http://127.0.0.1:8487 (CTRL + C to quit)
[2021-06-14 07:25:34 +0200] [10913] [INFO] Running on http://127.0.0.1:8487 (CTRL + C to quit)
[2021-06-14 07:25:34 +0200] [10916] [INFO] Running on http://127.0.0.1:8487 (CTRL + C to quit)
[2021-06-14 07:25:34 +0200] [10915] [INFO] Running on http://127.0.0.1:8487 (CTRL + C to quit)
[2021-06-14 07:25:34 +0200] [10907] [INFO] Running on http://127.0.0.1:8487 (CTRL + C to quit)
[2021-06-14 07:25:34 +0200] [10917] [INFO] Running on http://127.0.0.1:8487 (CTRL + C to quit)

**Comment by BerndHelber** [comment]
Looks good now :-)

**Comment by Someguy123** [comment]
Thanks for letting me know :)

Closing this issue now 👍
